### ISSUE TITLE
search functionality

### ISSUE THREAD

**Issue by abhilash61** [sriramkandukuri/automux#1]
currently we are unable to search string anywhere in the data, strict match is being forced currently

**Comment by sriramkandukuri** [comment]
https://github.com/sriramkandukuri/automux/commit/8a81bf0bab10638352a83caa31d83844c28729c8

Thank you for feedback, added requested feature. Please check latest code. 

below new functions added to verify substring in last line of the log, or to find the substring in whole log
```
automux_*_exec_expect_substr_*
automux_*_exec_findstr*
```

**Comment by sriramkandukuri** [comment]
mybad there is a typo in above message corrected now
