### ISSUE TITLE
Save Logs of Different Panes

### ISSUE THREAD

**Issue by pankitgarg** [sriramkandukuri/automux#3]
Can we have some utility using which we can save logs of different panes in a file without dumping to the host machine(i.e. on which script is executing)
e.g. Some commands lets say (log_start(filename)) starts saving logs to filename and log_stop stops the logs.

**Comment by sriramkandukuri** [comment]
please refer to `automux_log` apis in [readme](https://github.com/sriramkandukuri/automux/blob/main/README.md)
